modLoader="javafml"
loaderVersion="[32,)"
license="GPL v3"
[[mods]]
modId="miner_watcher"
version="1.0.1"
displayName="Miner Watcher"
authors="Tapio"
description='''
'''
[[dependencies.miner_watcher]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="SERVER"